[package]
name = "paulzyw02/preparation"
version = "0.1.0"
description = "Interview preparation material"
# Package configured for new deployment

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "dist"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
env = [
  "SERVER_PORT=80", 
  "SERVER_ROOT=/public", 
  "SERVER_PAGE_FALLBACK=/public/index.html",
  "SERVER_FALLBACK_PAGE=/public/index.html",
  "SERVER_ERROR_PAGE_404=/public/index.html"
]
